# Nixpacks configuration for Next.js with Prisma
[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "openssl", "sqlite"]

[phases.install]
cmds = [
  "npm ci --prefer-offline --no-audit",
  "npx prisma generate"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx prisma migrate deploy --skip-seed || true",
  "npm run build"
]

[start]
cmd = "npm run start:prod"

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"

# Health check configuration
[healthcheck]
path = "/api/health"
interval = "30s"
timeout = "3s"
retries = 3